[settings]
idiomatic_version_file_enable_tools = ["python"]

[tools]
aws-cli = "latest"
fzf = "latest"
jq = "latest"
uv = "latest"
node = "24"
go = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:aws-cdk" = "latest"
"npm:http-server" = "latest"
"npm:npm-check-updates" = "latest"
"npm:wscat" = "latest"
"npm:@antfu/ni" = "latest"
"npm:difit" = "latest"
pnpm = "latest"
gh = "latest"
hadolint = "latest"
starship = "latest"
zellij = "latest"
usage = "latest"
lazygit = "latest"
zoxide = "latest"
dive = "latest"
claude = "latest"
gemini = "latest"
jj = "latest"
